#if LITMOTION_SUPPORT_TMP
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;
using TMPro;

#if UNITY_EDITOR
using UnityEditor;
#endif

namespace LitMotion.Extensions
{
    public delegate void TMPCharacterMotionUpdateAction<T>(T value, int index, ref TMPMotionCharacter character);

    /// <summary>
    /// Values applied to a character on top of the mesh generated by TextMeshPro.
    /// </summary>
    public struct TMPMotionCharacter
    {
        /// <summary>
        /// Offset from the position TextMeshPro lays the character out at.
        /// </summary>
        public Vector3 Position;

        /// <summary>
        /// Scale around the center of the character.
        /// </summary>
        public Vector3 Scale;

        /// <summary>
        /// Rotation around the center of the character.
        /// </summary>
        public Quaternion Rotation;

        /// <summary>
        /// Tint multiplied with the vertex colors TextMeshPro generates for the character.
        /// </summary>
        public Color Color;
    }

    /// <summary>
    /// Wrapper class for animating individual characters in TextMeshPro.
    /// </summary>
    /// <remarks>
    /// Character values are applied to the vertices TextMeshPro generates, whenever TextMeshPro rebuilds the mesh and once per frame
    /// while motions change them. Values that aren't neutral are kept after the last motion ends, until they're reset.
    /// </remarks>
    internal sealed class TextMeshProMotionAnimator
    {
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]
        static void Init()
        {
#if UNITY_EDITOR
            var domainReloadDisabled = EditorSettings.enterPlayModeOptionsEnabled && EditorSettings.enterPlayModeOptions.HasFlag(EnterPlayModeOptions.DisableDomainReload);
            if (!domainReloadDisabled && initialized) return;
#else
            if (initialized) return;
#endif
            // PostLateUpdate runs after motions and scripts have written the frame's values, and before canvases rebuild meshes.
            PlayerLoopHelper.OnPostLateUpdate += UpdateAnimators;
            initialized = true;
        }

#if UNITY_EDITOR
        [InitializeOnLoadMethod]
        static void InitEditor()
        {
            EditorApplication.update += UpdateAnimatorsEditor;
        }
#endif

        static bool initialized;
        static TextMeshProMotionAnimator rootNode;

        static readonly TMPMotionCharacter neutralCharacter = new()
        {
            Position = Vector3.zero,
            Scale = Vector3.one,
            Rotation = Quaternion.identity,
            Color = Color.white,
        };

#if LITMOTION_TMP_LINEAR_VERTEX_COLORS
        // TextMeshPro 3.2 and later convert the vertex colors of TextMeshPro (3D) text in linear color space with an internal method, mirrored here.
        static readonly byte[] gammaToLinearTable = CreateGammaToLinearTable();
#endif

        internal static TextMeshProMotionAnimator Get(TMP_Text text)
        {
            if (textToAnimator.TryGetValue(text, out var animator))
            {
                // Other characters may be waiting on a delay or holding their final values, so the animator is never reset here.
                animator.refCount++;
                return animator;
            }

            // get or create animator
            animator = rootNode ?? new();
            rootNode = animator.nextNode;
            animator.nextNode = null;

            // set target
            animator.target = text;
            text.OnPreRenderText += animator.preRenderTextAction;

            // increment ref count
            animator.refCount++;

            // add to array
            if (tail == animators.Length)
            {
                Array.Resize(ref animators, tail * 2);
            }
            animators[tail] = animator;
            tail++;

            // add to dictionary
            textToAnimator.Add(text, animator);

            return animator;
        }

        internal static void Return(TextMeshProMotionAnimator animator)
        {
            animator.nextNode = rootNode;
            rootNode = animator;

            animator.target.OnPreRenderText -= animator.preRenderTextAction;
            textToAnimator.Remove(animator.target);
            animator.target = null;

            animator.SetNeutral(0);
            animator.refCount = 0;
            animator.isDirty = false;
            animator.holdsValues = false;
        }

        internal static void Reset(TMP_Text text)
        {
            if (!textToAnimator.TryGetValue(text, out var animator)) return;

            animator.SetNeutral(0);
            animator.holdsValues = false;
            animator.SetDirty();
        }

        static readonly Dictionary<TMP_Text, TextMeshProMotionAnimator> textToAnimator = new();
        static TextMeshProMotionAnimator[] animators = new TextMeshProMotionAnimator[8];
        static int tail;

        static void UpdateAnimators()
        {
            var j = tail - 1;

            for (int i = 0; i < animators.Length; i++)
            {
                var animator = animators[i];
                if (animator != null)
                {
                    if (!animator.TryUpdate())
                    {
                        Return(animator);
                        animators[i] = null;
                    }
                    else
                    {
                        continue;
                    }
                }

                while (i < j)
                {
                    var fromTail = animators[j];
                    if (fromTail != null)
                    {
                        if (!fromTail.TryUpdate())
                        {
                            Return(fromTail);
                            animators[j] = null;
                            j--;
                            continue;
                        }
                        else
                        {
                            animators[i] = fromTail;
                            animators[j] = null;
                            j--;
                            goto NEXT_LOOP;
                        }
                    }
                    else
                    {
                        j--;
                    }
                }

                tail = i;
                break;

            NEXT_LOOP:
                continue;
            }
        }

#if UNITY_EDITOR
        static void UpdateAnimatorsEditor()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode || EditorApplication.isCompiling || EditorApplication.isUpdating)
            {
                return;
            }
            UpdateAnimators();
        }
#endif

#if LITMOTION_TMP_LINEAR_VERTEX_COLORS
        static byte[] CreateGammaToLinearTable()
        {
            var table = new byte[256];
            for (int i = 0; i < table.Length; i++)
            {
                var value = i / 255f;
                if (value <= 0.04045f)
                {
                    table[i] = (byte)(value / 12.92f * 255f);
                }
                else if (value < 1f)
                {
                    table[i] = (byte)(Mathf.Pow((value + 0.055f) / 1.055f, 2.4f) * 255);
                }
                else
                {
                    table[i] = 255;
                }
            }
            return table;
        }
#endif

        public TextMeshProMotionAnimator()
        {
            charInfoArray = new TMPMotionCharacter[32];
            SetNeutral(0);

            preRenderTextAction = OnPreRenderText;
            motionEndAction = OnMotionEnd;
        }

        TMP_Text target;
        readonly Action<TMP_TextInfo> preRenderTextAction;
        internal readonly Action motionEndAction;
        internal TMPMotionCharacter[] charInfoArray;
        bool isDirty;
        bool holdsValues;
        int refCount;

        TextMeshProMotionAnimator nextNode;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void EnsureCapacity(int length)
        {
            var prevLength = charInfoArray.Length;
            if (length > prevLength)
            {
                Array.Resize(ref charInfoArray, Math.Max(length, prevLength * 2));
                SetNeutral(prevLength);
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Update()
        {
            TryUpdate();
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void SetDirty()
        {
            isDirty = true;
        }

        void SetNeutral(int startIndex)
        {
            for (int i = startIndex; i < charInfoArray.Length; i++)
            {
                charInfoArray[i] = neutralCharacter;
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        bool TryUpdate()
        {
            if (target == null) return false;

            if (isDirty)
            {
                Flush();
            }

            return refCount > 0 || isDirty || holdsValues;
        }

        void Flush()
        {
            // TextMeshPro rebuilds the mesh later this frame, and OnPreRenderText applies the characters to it.
            if (target.havePropertiesChanged) return;

            var textInfo = target.textInfo;
            Apply(textInfo);

            for (int i = 0; i < textInfo.materialCount; i++)
            {
                if (textInfo.meshInfo[i].mesh == null) continue;
                textInfo.meshInfo[i].mesh.colors32 = textInfo.meshInfo[i].colors32;
                textInfo.meshInfo[i].mesh.vertices = textInfo.meshInfo[i].vertices;
                target.UpdateGeometry(textInfo.meshInfo[i].mesh, i);
            }

            isDirty = false;
        }

        void OnPreRenderText(TMP_TextInfo textInfo)
        {
            Apply(textInfo);
            isDirty = false;
        }

        void OnMotionEnd()
        {
            // A preserved motion can be canceled after it has already completed.
            if (refCount == 0) return;

            refCount--;
            if (refCount == 0)
            {
                holdsValues = !IsNeutral();
            }
        }

        void Apply(TMP_TextInfo textInfo)
        {
            var characterCount = textInfo.characterCount;
            EnsureCapacity(characterCount);

            // characterInfo keeps the vertices TextMeshPro generated, so every pass starts from the unmodified character.
            var characterInfos = textInfo.characterInfo;
            var meshInfos = textInfo.meshInfo;
#if LITMOTION_TMP_LINEAR_VERTEX_COLORS
            var convertToLinear = target is TextMeshPro && QualitySettings.activeColorSpace == ColorSpace.Linear;
#else
            var convertToLinear = false;
#endif

            for (int i = 0; i < characterCount; i++)
            {
                ref var charInfo = ref characterInfos[i];
                if (!charInfo.isVisible) continue;

                ref var motionCharInfo = ref charInfoArray[i];
                var vertices = meshInfos[charInfo.materialReferenceIndex].vertices;
                var colors = meshInfos[charInfo.materialReferenceIndex].colors32;
                var vertexIndex = charInfo.vertexIndex;

                var bottomLeft = charInfo.vertex_BL.position;
                var topLeft = charInfo.vertex_TL.position;
                var topRight = charInfo.vertex_TR.position;
                var bottomRight = charInfo.vertex_BR.position;

                if (IsNeutralTransform(motionCharInfo))
                {
                    vertices[vertexIndex] = bottomLeft;
                    vertices[vertexIndex + 1] = topLeft;
                    vertices[vertexIndex + 2] = topRight;
                    vertices[vertexIndex + 3] = bottomRight;
                }
                else
                {
                    var center = (bottomLeft + topRight) * 0.5f;
                    vertices[vertexIndex] = TransformVertex(bottomLeft, center, motionCharInfo);
                    vertices[vertexIndex + 1] = TransformVertex(topLeft, center, motionCharInfo);
                    vertices[vertexIndex + 2] = TransformVertex(topRight, center, motionCharInfo);
                    vertices[vertexIndex + 3] = TransformVertex(bottomRight, center, motionCharInfo);
                }

                var tint = motionCharInfo.Color;
                var isNeutralTint = tint == Color.white;
                colors[vertexIndex] = GetVertexColor(charInfo.vertex_BL.color, tint, isNeutralTint, convertToLinear);
                colors[vertexIndex + 1] = GetVertexColor(charInfo.vertex_TL.color, tint, isNeutralTint, convertToLinear);
                colors[vertexIndex + 2] = GetVertexColor(charInfo.vertex_TR.color, tint, isNeutralTint, convertToLinear);
                colors[vertexIndex + 3] = GetVertexColor(charInfo.vertex_BR.color, tint, isNeutralTint, convertToLinear);
            }
        }

        bool IsNeutral()
        {
            for (int i = 0; i < charInfoArray.Length; i++)
            {
                ref var motionCharInfo = ref charInfoArray[i];
                if (!IsNeutralTransform(motionCharInfo) || motionCharInfo.Color != Color.white) return false;
            }

            return true;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static bool IsNeutralTransform(in TMPMotionCharacter motionCharInfo)
        {
            return motionCharInfo.Position == Vector3.zero &&
                motionCharInfo.Scale == Vector3.one &&
                Mathf.Abs(motionCharInfo.Rotation.w) > 1f - Quaternion.kEpsilon;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static Vector3 TransformVertex(Vector3 vertex, Vector3 center, in TMPMotionCharacter motionCharInfo)
        {
            var dir = vertex - center;
            var scale = motionCharInfo.Scale;
            return center + motionCharInfo.Rotation * new Vector3(dir.x * scale.x, dir.y * scale.y, dir.z * scale.z) + motionCharInfo.Position;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static Color32 GetVertexColor(Color32 color, Color tint, bool isNeutralTint, bool convertToLinear)
        {
            if (!isNeutralTint)
            {
                color.r = MultiplyChannel(color.r, tint.r);
                color.g = MultiplyChannel(color.g, tint.g);
                color.b = MultiplyChannel(color.b, tint.b);
                color.a = MultiplyChannel(color.a, tint.a);
            }

#if LITMOTION_TMP_LINEAR_VERTEX_COLORS
            if (convertToLinear)
            {
                color.r = gammaToLinearTable[color.r];
                color.g = gammaToLinearTable[color.g];
                color.b = gammaToLinearTable[color.b];
            }
#endif

            return color;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static byte MultiplyChannel(byte channel, float tint)
        {
            var value = channel * tint + 0.5f;
            if (value <= 0f) return 0;
            if (value >= 255f) return 255;
            return (byte)value;
        }
    }
}
#endif